version: "2"

networks:
  proxy-tier:
    external:
      name: caddy-proxy

services:
  caddy:
    container_name: caddy
    image: drlogout/caddy:0.9.5
    # remove -ca=https://acme-staging.api.letsencrypt.org/directory in production
    command: -conf /etc/caddy/config/Caddyfile -log stdout -agree
    ports:
      - 80:80
      - 443:443
    volumes:
      - "caddyconfig:/etc/caddy/config"
      - "caddycerts:/etc/caddy/certs"
    environment:
      - CADDYPATH=/etc/caddy/certs
    networks:
      - proxy-tier
    restart: always

  caddy-gen:
    container_name: caddy-gen
    build:
      context: ..
      dockerfile: caddy/Dockerfile-docker-gen
    volumes:
      - "/var/run/docker.sock:/tmp/docker.sock:ro"
    volumes_from:
      - caddy
    environment:
      LETSENCRYPT_EMAIL: "email@example.com"
    command: -config /etc/docker-gen/config/docker-gen.cfg
    restart: always

volumes:
  caddyconfig:
    driver: local
  caddycerts:
    driver: local
